site_name: cPython - 给大学生的入门教程
pages:
    - 关于本站: index.md
    - 开始: start.md
    - 变量: variables.md
    - 字符串: string.md
    - 列表: list.md
    - 元组: tuple.md
    - range: range.md
    - For: for.md
    - If: if.md
    - 切片／slice: slice.md
    - dict: dict.md
    - 函数: functions.md
    - 模块: module.md
    - 安装模块（pip）: pip.md
    - 类: class.md
    - 随机数: rand.md
    - 正则: re.md
    - 字符串函数: string_func.md
    - 列表函数: list_func.md
    - 时间函数: time.md
    - 文件处理: file.md
    - 错误和异常: error_except.md
    - 调试: debug.md
    - 常用内置函数: built_in_func.md
    - requests: requests.md
theme: readthedocs
